import type { Metadata } from "next";
import { Alexandria } from "next/font/google";
import { Toaster } from "@/components/ui/sonner"
import "./globals.css";

const alexandriaSans = Alexandria({
  variable: "--font-alexandria"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${alexandriaSans.variable} antialiased`}
      >
        {children}
        <Toaster position="top-center" richColors/>
      </body>
    </html>
  );
}
